# -*- mode: ruby -*-
# vi: set ft=ruby :

# Load in custom vagrant settings
require "yaml"
settings = File.file?("vagrant.yml") ? YAML.load_file("vagrant.yml") : {}
puts "== Using Settings From vagrant.yml =="
puts settings.inspect

VAGRANTFILE_API_VERSION = "2".freeze
$box = settings["vagrant-name"]
$ip = settings["network"]["ip"]
$hostname = settings["network"]["hostname"]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  ### Work Around to Fix Vagrant Bug in
  # correctly assigning the provided name to the box
  config.vm.define settings["vagrant-name"] do |t|
  end
  config.vm.provider "virtualbox" do |p|
    p.name = $box
  end
  ### Workaround Ends ###

  config.vm.box = "minimal/trusty64"
  config.vm.hostname = $hostname
  config.vbguest.auto_update = true


  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.customize ["modifyvm", :id, "--usb", "off"]
  end

  config.vm.network "private_network", ip: $ip
  config.hostsupdater.aliases = [$hostname]

   config.vm.provision "ansible" do |ansible|
     ansible.playbook = "ansible/site.yml"
   end
  
  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 3000, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../../dashboard/", "/vagrant/dashboard"
end
